### ISSUE TITLE
VCRFT Cannot Install Module

### ISSUE THREAD

**Issue by SpaceD0lphin** [regzo2/VRCFaceTracking-QuestProOpenXR#3]
Hello, I am new to this. 

Installing the OpenXR Module from the Modules list in VRCFT 5.1.1.0 appears to have no result. The app continually shows "No Modules Loaded" upon startup.
Output says this is because it failed to get XrSystemID.

Manual installation of other OpenXR .zip files fail due to the modules not containing module.json - I don't know what that is. Here is my output log:

![image](https://github.com/regzo2/VRCFaceTracking-QuestProOpenXR/assets/79815367/4380b384-98c7-4d72-aa4f-dff9b539509a)

Thanks for any assistance.

**Comment by mooggsentry** [comment]
Same issue

**Comment by SpaceD0lphin** [comment]
> Same issue

Hello,
Since writing this issue I have solved the problem. It may be useful to write something about this in future documentation, as it's a step easily missed in most tutorials.

Ensure your headset itself is in Developer Mode.

To do this, you will need to register yourself as a developer on developer.oculus.com, and then use the Meta companion app on your mobile phone to manage the device. From there, you can set the Pro to Developer mode.

OpenXR should then be able to hook in.

**Comment by regzo2** [comment]
Developer mode will not be required anymore, so this will not be an issue going forward. The module is being reworked to better handle errors and give much better feedback as well!
