### ISSUE TITLE
Incorrect Quaternion Usage for Right Eye Gaze Calculation (Maybe)

### ISSUE THREAD

**Issue by faker2048** [regzo2/VRCFaceTracking-QuestProOpenXR#4]
https://github.com/regzo2/VRCFaceTracking-QuestProOpenXR/blob/7c86537b5342a82ec682147dc77b2ca1805eab78/VRCFT%20-%20Quest%20OpenXR/QuestOpenXRTrackingModule.cs#L256

This only use orientation_L , maybe should be orientation_R

**Comment by regzo2** [comment]
Will be fixed in https://github.com/regzo2/VRCFaceTracking-QuestProOpenXR/pull/5
