### ISSUE TITLE
Puckering Lips causes Inner Eye Brows to lower

### ISSUE THREAD

**Issue by Antarcticsiclepop** [regzo2/VRCFaceTracking-QuestProOpenXR#8]
When Puckering Lips the Inner Eye Brows will lower even if they don't move.

**Comment by regzo2** [comment]
There isn't anything in my code that would cause that behavior

https://github.com/regzo2/VRCFaceTracking-QuestProOpenXR/blob/05763c4722a027a45471c89e29a273baf2bb5391/VRCFT%20-%20Quest%20OpenXR/QuestOpenXRTrackingModule.cs#L175-L183

https://github.com/regzo2/VRCFaceTracking-QuestProOpenXR/blob/05763c4722a027a45471c89e29a273baf2bb5391/VRCFT%20-%20Quest%20OpenXR/QuestOpenXRTrackingModule.cs#L239-L247

It sounds more like an avatar issue.

**Comment by Antarcticsiclepop** [comment]
Issue is the template.
