### ISSUE TITLE
NoseSneer Trigger MouthUpperUp

### ISSUE THREAD

**Issue by Adjerry91** [regzo2/VRCFaceTracking-QuestProOpenXR#9]
NoseSneer is triggering MouthUpperUp even there is compensation in the code to cancel it out. Looking at the code there looks to be calibration in the code that is separate from the VRCFT calibration. Integrated calibration should not be included in modules as this adds confusion.

![image](https://github.com/user-attachments/assets/171fbd8d-53aa-4e9c-9585-a82d4e0660ff)

**Comment by regzo2** [comment]
There is no calibration feature in the code base. The updated release has yet to be accepted on the registry.
